services:
  dotnet:
    container_name: dotnet
    image: ghcr.io/sakuexe/portfolio:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dotnet-fullstack-portfolio.rule=Host(`localhost`)"
      - "traefik.http.routers.dotnet-fullstack-portfolio.entrypoints=web"
    env_file: .env
    depends_on:
      - mongodb
    volumes:
      # maintains the files between container restarts
      - uploaded_files:/App/wwwroot/uploads
    networks:
      - default

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

  traefik:
    container_name: reverse-proxy
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      # Web UI
      - "8080:8080"
    volumes:
      # allow Traefik to listen for docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    depends_on: 
      - dotnet

networks:
  default:
volumes:
  mongodb_data:
  uploaded_files:
