services:
  watchtower:
    # watchtower checks for new pushes to the portfolio image
    # and then pulls them automatically
    # https://containrrr.dev/watchtower
    image: containrrr/watchtower
    command:
      # https://containrrr.dev/watchtower/arguments
      - "--label-enable"
      - "--interval"
      - "30"
      # incrementally update the containers, instead of all at once
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  umbraco_backend:
    image: ghcr.io/sakuexe/portfolio:prod
    platform: linux/arm64
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ConnectionStrings__umbracoDbDSN=Data Source=|DataDirectory|/Umbraco.sqlite.db;Cache=Shared;Foreign Keys=True;Pooling=True
      - ConnectionStrings__umbracoDbDSN_ProviderName=Microsoft.Data.Sqlite
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umbraco_backend.rule=Host(`api.sakukarttunen.com`)"
      - "traefik.http.routers.umbraco_backend.entrypoints=web"
      - "traefik.http.services.umbraco_backend.loadbalancer.server.port=8080"
    volumes:
      - ./media:/app/portfolio/wwwroot/media
      - ./logs:/app/portfolio/umbraco/Logs
      - ./umbraco_data:/app/portfolio/umbraco/Data
    restart: always
    env_file: ".env"
