services:
  dotnet:
    container_name: dotnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dotnet-fullstack-portfolio.rule=Host(`localhost`)"
      - "traefik.http.routers.dotnet-fullstack-portfolio.entrypoints=web"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      # set the environment variable to connect to the mongodb container
      # the value is in ConnectionStrings > DefaultConnection
      - ConnectionStrings__DefaultConnection=mongodb
      - ConnectionStrings__DatabaseName=portfolio
      # the base(d) admin user for the application
      - Admin__Username=root
      - Admin__Password=rootroot
      # email settings - do NOT use double quotes in the value (fuck)
      - Email__Address=example@email.com
      - Email__Password=one two three four
      - Email__Recipient=me@gmail.com
      # logging settings
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    depends_on:
      - mongodb
    volumes:
      # maintains the files between container restarts
      - uploaded_files:/App/wwwroot/uploads
    networks:
      - default

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

  traefik:
    container_name: reverse-proxy
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      # Web UI
      - "8080:8080"
    volumes:
      # allow Traefik to listen for docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
    depends_on: 
      - dotnet

networks:
  default:

volumes:
  mongodb_data:
  uploaded_files:
