services:
  backend:
    image: ghcr.io/sakuexe/portfolio:prod
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ConnectionStrings__umbracoDbDSN=Data Source=|DataDirectory|/Umbraco.sqlite.db;Cache=Shared;Foreign Keys=True;Pooling=True
        - ConnectionStrings__umbracoDbDSN_ProviderName=Microsoft.Data.Sqlite
    volumes:
      - umb_media:/app/portfolio/wwwroot/media
      - umb_logs:/app/portfolio/umbraco/Logs
      - umb_data:/app/portfolio/umbraco
      - ./database.sqlite3:/app/portfolio/umbraco/Data/Umbraco.sqlite.db
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - umbnet

volumes:
  umb_media:
  umb_logs:
  umb_data:

networks:
  umbnet:
