services:
  watchtower:
    # watchtower checks for new pushes to the portfolio image
    # and then pulls them automatically
    # https://containrrr.dev/watchtower
    image: containrrr/watchtower
    command:
      # https://containrrr.dev/watchtower/arguments
      - "--label-enable"
      - "--interval"
      - "30"
      # incrementally update the containers, instead of all at once
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    container_name: traefik
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      # TLS (https)
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=saku.karttunen@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # http redirection
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      # logs
      - "--log.level=WARN"
      - "--log.format=json"
    ports:
      - "80:80"
      - "443:443"
      # Web UI
      - "8080:8080"
    volumes:
      # allow Traefik to listen for docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # persist the ssl certificate
      - letsencrypt:/letsencrypt
    networks:
      - default
    depends_on: 
      - portfolio

  portfolio:
    image: ghcr.io/sakuexe/portfolio:prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dotnet.rule=Host(`fs.sakukarttunen.com`)"
      - "traefik.http.routers.dotnet.entrypoints=websecure"
      - "traefik.http.routers.dotnet.tls.certresolver=myresolver"
      # local development
      # - "traefik.http.routers.dotnet.rule=Host(`localhost`)"
      # - "traefik.http.routers.dotnet.entrypoints=websecure"
      # enable watchtower
      - "com.centurylinklabs.watchtower.enable=true"
    env_file: .env
    depends_on:
      - mongodb
    volumes:
      # maintains the files between container restarts
      - uploaded_files:/App/wwwroot/uploads
    networks:
      - default
    ports:
      - "80"
      - "443"
    deploy:
      replicas: 1 # adjust as needed

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodb_data:/data/db
    networks:
      - default

networks:
  default:
volumes:
  mongodb_data:
  uploaded_files:
  letsencrypt:
