name: build-and-push-docker-image

on:
  push:
    branches: ['main']

env:
  GITHUB_REGISTRY: ghcr.io
  DOCKER_IMAGE: ${{ github.repository }}
  DOCKER_TAG_NAME: prod

jobs:
  build-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout the repo
        uses: actions/checkout@v4

      - name: login to ghcr.io
        # run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.repository.owner }} --password-stdin ${{ env.GITHUB_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.FINE_GRAINED_TOKEN }}

      - name: build and push docker image using buildx
        run: |
          docker build -t ${{ env.GITHUB_REGISTRY }}/${{ github.actor }}/${{ github.repository }}:${{ env.DOCKER_TAG_NAME }} .
          docker push ${{ env.GITHUB_REGISTRY }}/${{ github.actor }}/${{ github.repository }}:${{ env.DOCKER_TAG_NAME }}
